sudo: required

services:
    - docker

before_install:
    - docker build -t martinmoserswiss/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true martinmoserswiss/docker-react npm run test